### ISSUE TITLE
Combine Latest only emits after all have emitted at least once

### ISSUE THREAD

**Issue by MichaelObi** [adibfara/Lives#19]
The current implementation of `combineLatest` only emits if all the two LiveData objects have emitted at least once. I think this is because of the check in this line
https://github.com/adibfara/Lives/blob/df825fa891beee250aa866004924b6966133281a/lives/src/main/java/com/snakydesign/livedataextensions/Combining.kt#L175

I think the check on that line should be a `||` instead of `&&`
I need to confirm that I'm not wrong.

Feedback will be appreciated

**Comment by adibfara** [comment]
It would throw an NPE if one of them has not emitted yet.
This line exists so that it can ensure that all live data object have emitted. 
Nullable values for the 'emitted value of live data' won't work since the live data object can be Nullable and emit null.

**Comment by MichaelObi** [comment]
My thoughts are that the current implementation ultimately works the same way as `zip`.
I'd understand that this holds in an Rx scenario where nulls cannot be emitted, but for `LiveData` that allows nulls, I think that it's possible to make the combine functions take in nullable parameters.
The current implementations  require that we always initialise the component `Livedata`s with nulls when the `ViewModel` is created

**Comment by adibfara** [comment]
I don't completely understand the issue, could you elaborate more? Current implementation handles both nullable and non-null LiveData objects.

**Comment by brudaswen** [comment]
I think it is correct, that `zip` and `combineLatest` only emit after all sources have emitted at least one value. The `&&` is therefore correct.
See: http://reactivex.io/documentation/operators/combinelatest.html

However, you are right that the current implementation does not support `null` values in the LiveData. See #20.

**Comment by MichaelObi** [comment]
Thanks @brudaswen, @adibfara.
I think that clears it up for me.
