### ISSUE TITLE
Zip and CombineLatest crash when null values are posted

### ISSUE THREAD

**Issue by brudaswen** [adibfara/Lives#20]
The implementation of `zip` and `combineLatest` assume that the posted value is never null:
https://github.com/adibfara/Lives/blob/5fc4b9c910af0c201dd3c817285f8ad73a22a27b/lives/src/main/java/com/snakydesign/livedataextensions/Combining.kt#L80

However, this is not true:
```kotlin
val x = MutableLiveData<Int?>()
val y = MutableLiveData<Int>()
val r = zip(x, y).observeForever { }
x.value = null
y.value = 42 // CRASH due to null value!
```

I am preparing a PR to fix that.

**Comment by krage** [comment]
I was looking for a combineLatest and wound up here after encountering the same crash.  This repo seems a bit abandoned but if it's ever revived I think it'd be nice to offer overloads at least for all nullable sources vs no nullable sources.

Allows nullable sources so combiner must handle nulls:
```kotlin
fun <X, Y, Z, R> combineLatest(first: LiveData<X>, second: LiveData<Y>, third: LiveData<Z>, combineFunction: (X?, Y?, Z?) -> R): LiveData<R>
```

Doesn't allow nullable sources so combiner doesn't need to handle nulls:
```kotlin
fun <X: Any, Y: Any, Z: Any, R> combineLatest(first: LiveData<X>, second: LiveData<Y>, third: LiveData<Z>, combineFunction: (X, Y, Z) -> R): LiveData<R>
```

**Comment by Zhuinden** [comment]
I have no implementation of `zip`, but I specifically wrote https://github.com/Zhuinden/livedata-combinetuple-kt/ in such a way that this wouldn't be a problem for `combineLatest`.

**Comment by adibfara** [comment]
Thanks everyone. Both these operators had me thinking about how they are gonna handle nulls. I tried to go with the non-null version, but I think going with the nullable option is better since LiveData itself is designed that way.
