### ISSUE TITLE
Using a nonNull doesnt emit after pause/resume

### ISSUE THREAD

**Issue by aidanmack** [adibfara/Lives#22]
Steps to reproduce...
If I use a nonNull operator, 
observe the nonnull `Livedata`, the data that is not null is emitted
Pause app
Resume app
Data is no longer emitted

My fix for this was to...
restart the observer onActive.

In doing so I could not see a usecase for the init anymore?

Also... Is it ok to use ObserveForever in a livedata? I thought that was a no no.

```
class NonNullLiveData<T>(private val liveData: LiveData<T>) : LiveData<T>() {
    private val mediatorLiveData = MediatorLiveData<T>()
    private val mediatorObserver = Observer<T> {
        it?.let {
            this@NonNullLiveData.value = it
        }
    }

//    init {
//        mediatorLiveData.observeForever(mediatorObserver)
//        mediatorLiveData.addSource(liveData, mediatorObserver)
//    }

    override fun onInactive() {
        super.onInactive()
        mediatorLiveData.removeObserver(mediatorObserver)
    }

    override fun onActive() {
        super.onActive()
        mediatorLiveData.observeForever(mediatorObserver)
        mediatorLiveData.addSource(liveData, mediatorObserver)
    }

}
```

**Comment by Zhuinden** [comment]
You are correct, he should not remove the observer inside `onInactive`.

In fact, this shouldn't be done via inheritance + MediatorLiveData, it would be best to return a MediatorLiveData as a LiveData from `.nonNull()` in the first place.

> ``` kotlin
> fun <T> LiveData<T>.nonNull(): NonNullLiveData<T> {
>     return NonNullLiveData(this)
> }
> 
> class NonNullLiveData<T>(liveData:LiveData<T>) : LiveData<T>() {
>     private val mediatorLiveData = MediatorLiveData<T>()
>     private val mediatorObserver = Observer<T> {
>         it?.let{
>             this@NonNullLiveData.value = it
>         }
>     }
>     init {
>             mediatorLiveData.observeForever(mediatorObserver)
>             mediatorLiveData.addSource(liveData, mediatorObserver)
>     }
>     override fun onInactive() {
>         super.onInactive()
>         mediatorLiveData.removeObserver(mediatorObserver)
>     }
> }
> ```

should have been as simple as

``` kotlin
fun <T> LiveData<T>.nonNull(): LiveData<T> = MediatorLiveData<T>.also { mediator ->
    val value = this.value
    if(value != null) {
        mediator.setValue(value)
    }

    mediator.addSource(this) { value ->
        if(value != null) {
            mediator.setValue(value)
        }
    }
}
```

And then there is no need for internal subscription beyond what `MediatorLiveData` does internally.

**Comment by Zhuinden** [comment]
Interestingly, there was a pending PR since about a year ago (April 2019) https://github.com/adibfara/Lives/pull/17
