### ISSUE TITLE
distinctUntilChanged doesn't emit first null emission

### ISSUE THREAD

**Issue by aromano272** [adibfara/Lives#25]
If the source emits a null as its first emission, distinctUntilChanged operator will filter that emission and will not emit it because the initial value of `latestValue` will be the same as the emission.

Google's official Transformations package already includes this method, it would be better if distinctUntilChanged called the Transformations instead.

**Comment by adibfara** [comment]
Thanks. Version 2.0.0 will use the one from LiveData KTX.
