### ISSUE TITLE
Consider allowing `just` method to emit a null value

### ISSUE THREAD

**Issue by curioustechizen** [adibfara/Lives#3]
Currently the implementation of `just` checks that the initial value passed in is not null and [only then it sets the initial value](https://github.com/adibfara/Lives/blob/3904942ec0c5ae6938fd170e13ac782dfb2326e4/lives/src/main/java/com/snakydesign/livedataextensions/Creating.kt#L17-L18) to the LiveData. This means the following code will result in no emissions and hence the observer will never be called. The expected behavior is for the observer to be called with a `null` value.

```kotlin
just(null).observeForever(observer)
```

The "solution" is to remove that null-check. I could submit a PR along with tests for this. But before I do that I would like to know whether there is a reason that null-check is there? Is it intentional?

**Comment by curioustechizen** [comment]
I thought about this a bit more and I can foresee there are situations where you do not want to emit immediately when the LiveData is created. For such cases you could add an `empty()` function as follows:

```kotlin
fun <T> empty(): LiveData<T> = MutableLiveData<T>()
```

This way, `just` could be implemented as 

```kotlin
fun <T> just(initialValue: T): LiveData<T> = MutableLiveData<T>().apply { value = initialValue }
```

**Comment by adibfara** [comment]
I was conflicted with this one too, but having a `just` with null values seemed a bit weirder than the non-null one.
You suggestion makes sense (and I will add the `empty` operator) but the user has to push a null into it for the first null (which makes sense to me, since it is not a general thing).

**Comment by curioustechizen** [comment]
>  but the user has to push a null into it for the first null

Of course. The way I'm thinking about it is: if you don't want to emit on initialization, use `empty()`. If you do, use `just()` (passing `null` or whatever other value).

One point to consider is whether `empty()` should return `LiveData` or `MutableLiveData()`. If it only returns `LiveData` then the return value would be useless since it can never be updated outside the function (unless I'm missing some other way to update it).

By the way do you want me to send a PR for this? Or would you rather do it yourself?

**Comment by adibfara** [comment]
I am doing it right away. Returning `MutableLiveData` is more logical. You could think of `empty` as a short-hand for `MutableLiveData<T>()`.
