### ISSUE TITLE
[Feature Request] API for testing

### ISSUE THREAD

**Issue by juliocbcotta** [adibfara/Lives#4]
Hi, it would be nice to have a rx like api for unit testing LiveData...
something like
``` kotlin
val testObserver = vm.liveData.test()

// do test setup stuff

testObserver.assertValues(listOf("A", "B"))
.assertNoValues()
.dispose()

```

**Comment by adibfara** [comment]
Hello, It is very nice to have that, but I think it is out of scope of this library. 

All PR's are welcome though, since all my tests are done with the regular testing framework for LiveData.
