### ISSUE TITLE
Possible minor improvement on take(count)

### ISSUE THREAD

**Issue by BoD** [adibfara/Lives#6]
Hi!  This is not really an issue, but rather a potential minor improvement.  Would it make sense to slightly modify `take` like so?

```
fun <T> LiveData<T>.take(count: Int): LiveData<T> {
    val mutableLiveData: MediatorLiveData<T> = MediatorLiveData()
    var takenCount = 0
    mutableLiveData.addSource(this) {
        if (takenCount < count) {
            mutableLiveData.value = it
            takenCount++

            if (takenCount == count) mutableLiveData.removeSource(this) // <- here
        }
    }
    return mutableLiveData
}
```

We remove the source when we reach the desired count, instead of continuing to listen to it but ignoring the values.  I'm not 100% positive this won't break something that's why I prefer to ask your opinion first.  Thoughts?

**Comment by adibfara** [comment]
Thanks for your suggestion, It makes sense to remove the source from the returned LiveData as we don't have anything to do with the source after that.
