### ISSUE TITLE
Unresolved reference when building

### ISSUE THREAD

**Issue by k0shk0sh** [adibfara/Lives#7]
lib version: 1.0.1
arch components libs version: 2.0.0

I'm having some weird issues for anyone who is trying to clone my branch and build it themselves, even CI fails to build the app, however on my machine everything is working fine. 

I'm getting the following error when trying to build via CI: 

```
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch
```

specifically in this line: https://github.com/k0shk0sh/FastHub/blob/fasthub/fasthub-v5/data/src/main/java/com/fastaccess/data/repository/NotificationRepositoryProvider.kt#L17

I went and changed that line to use the `Transformations.map()` and that fun passed however i'm doing more of `map & switchMap` in https://github.com/k0shk0sh/FastHub/blob/fasthub%2Ffasthub-v5/app/src/main/java/com/fastaccess/github/ui/modules/main/fragment/viewmodel/MainFragmentViewModel.kt#L36 which causes more related issues. 

the full log: 
```
e: /bitrise/src/data/src/main/java/com/fastaccess/data/repository/NotificationRepositoryProvider.kt: (17, 10): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun <T, O> LiveData<List<NotificationModel>>.map(function: MapperFunction<List<NotificationModel>, ???> /* = (List<NotificationModel>) -> ??? */): LiveData<???> defined in com.snakydesign.livedataextensions
```

i'm not sure if this is a kotlin limitation or something i'm missing. 

Thanks

**Comment by adibfara** [comment]
It might be because of the updated version of the Architecture Components library (they probably changed the signature of a function)

Will have to investigate

**Comment by adibfara** [comment]
Please check with the new release (1.2.0) and let me know if your issue still exists.
